# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCTeam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~>3.8'
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  pod 'ImageSlideshow', '~> 1.1.0'
  pod 'ImageSlideshow/SDWebImage'
  pod 'SCLAlertView'
  pod 'Gifu'
  # Pods for SCBraga

end
